[theme]
primaryColor = "#0F72E8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1F2937"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
